@startuml BaseMHS

class BaseMHS {
    - HypothesisFactory factory
    - List<Hypothesis> current
    - List<Hypothesis> solutions
    - boolean[][] instance
    - boolean[][] matrix
    - List<Integer> nonEmptyColumns
    - int DEPTH
    - int depthLimit
    - double computationTime
    - boolean executed
    - boolean stopped
    - boolean stoppedInsideLoop

    + BaseMHS(boolean[][] instance)
    - Hypothesis getInitialHypothesis(BitSetType type, int m, int n)
    - List<Hypothesis> generateChildrenEmptyHypothesis(Hypothesis parent)
    - List<Hypothesis> generateChildren(Hypothesis parent)
    - Hypothesis binarySearch(Hypothesis target)
    - static boolean isGreater(Hypothesis h1, Hypothesis h2)
    - List<Hypothesis> merge(Collection<Hypothesis> hypotheses, Collection<Hypothesis> toMerge)
    - void setFields(Hypothesis hypothesis)
    - boolean check(Hypothesis hypothesis)
    - void propagate(Hypothesis predecessor, Hypothesis successor)
    - void cleanMatrix()
    - void restoreSolutions()
}
@enduml
