@startuml
!pragma layout smetana

class BitSetHypothesis {
    - bin : BitSetAdapter
    - vector : BitSetAdapter
    + BitSetHypothesis(size : int, n : int)
    + BitSetHypothesis(vector : BitSetAdapter)
}

@enduml