@startuml BitSetAdapter

class BitSetAdapter {
    - final BitSet bitSet
    - final int size

    + BitSetAdapter(int size)
    - BitSetAdapter(BitSetAdapter original)

    + void and(BitSetAdapter other)
    + void or(BitSetAdapter other)
    + void xor(BitSetAdapter other)
    + BitSetAdapter clone()
    + boolean equals(Object o)
    + int hashCode()
}
@enduml
