@startuml

class BooleanSet {
    - boolean[] bits

    + BooleanSet(boolean[] bin)
    + BooleanSet(int size)
    + boolean[] getBools()
    + BooleanSet clone()
    + int hashCode()
    + boolean equals(Object o)
}
@enduml
