@startuml

class BoostMHS {
    - HypothesisFactory factory
    - PriorityQueue<Hypothesis> current
    - List<Hypothesis> solutions
    - LinkedHashMap<BitVector, BitVector> bucket
    - boolean[][] instance
    - boolean[][] matrix
    - List<Integer> nonEmptyColumns
    - int DEPTH
    - long startTime
    - int depthLimit
    - double computationTime
    - boolean executed
    - boolean stopped
    - boolean stoppedInsideLoop
    - boolean outOfMemoryError

    + BoostMHS(boolean[][] instance)
    - Hypothesis getInitialHypothesis(BitSetType type, int m, int n)
    - List<Hypothesis> generateChildrenEmptyHypothesis(Hypothesis parent)
    - List<Hypothesis> generateChildren(Hypothesis parent)
    - static boolean isGreater(BitVector a, BitVector b)
    - void setFields(Hypothesis hypothesis)
    - boolean check(Hypothesis hypothesis)
    - void propagate(Hypothesis predecessor, Hypothesis successor)
    - void cleanMatrix()
    - void restoreSolutions()
}
@enduml
