@startuml

class FastBitSet {
    + final int logicalSize
    + final long[] words

    + FastBitSet(int size)
    + long[] words()
    + void or(FastBitSet other)
    + void and(FastBitSet other)
    + void andNot(FastBitSet other)
    + void xor(FastBitSet other)
    + int nextSetBit(int fromIndex)
    + int previousSetBit(int fromIndex)
    + boolean equals(Object obj)
    + int hashCode()
}
@enduml
