@startuml

class RoaringBitmapAdapter {
    - final RoaringBitmap bitmap
    - final int size

    + RoaringBitmapAdapter(int size)
    + void or(RoaringBitmapAdapter other)
    + void xor(RoaringBitmapAdapter other)
    + RoaringBitmapAdapter clone()
    + int hashCode()
    + boolean equals(Object o)
}
@enduml
