@startuml
!pragma layout smetana

class RoaringHypothesis {
    - bin : RoaringBitmapAdapter
    - vector : RoaringBitmapAdapter
    + RoaringHypothesis(size : int, n : int)
    + RoaringHypothesis(h : RoaringBitmapAdapter)
}

@enduml