@startuml

class SparseVector {
    - final SparseBitSet bitmap
    - int size

    + SparseVector(int size)
    + SparseVector clone()
    + void or(SparseVector other)
    + boolean equals(Object obj)
    + int hashCode()
}
@enduml
